name: wolzarm_flutter_cli
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/taloengrat-p/wolzarm_flutter_cli
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  args: any
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
